### PR TITLE
Fix -Werror=cast-function-type with GCC 8

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by monsta** [comment]
GLib developers went as far as adding a new macro for silencing similar warning when casting to `GSourceFunc`...

```C
#define G_SOURCE_FUNC(f) ((GSourceFunc) (void (*)(void)) (f))
```

See https://github.com/mate-desktop/marco/pull/465 and the link inside.

**Comment by raveit65** [comment]
What we do with that PR, closing?

**Comment by raveit65** [comment]
@mate-desktop/core-team @vkareh @monsta @rbuj 
Again, What should we do with that PR, closing?

**Comment by rbuj** [comment]
I think it's obsolete now. I reviewed the build log and I found only 7 warnings:
```
matekbd-status.c:105:2: warning: ‘gtk_status_icon_set_tooltip_text’ is deprecated [-Wdeprecated-declarations]
matekbd-status.c:547:2: warning: ‘gtk_status_icon_set_from_pixbuf’ is deprecated [-Wdeprecated-declarations]
matekbd-status.c:570:9: warning: ‘gtk_status_icon_get_x11_window_id’ is deprecated [-Wdeprecated-declarations]
matekbd-keyboard-drawing.c:1252:3: warning: ‘gtk_style_context_get_background_color’ is deprecated: Use 'gtk_render_background' instead [-Wdeprecated-declarations]
matekbd-keyboard-drawing.c:1568:2: warning: ‘gtk_style_context_get_background_color’ is deprecated: Use 'gtk_render_background' instead [-Wdeprecated-declarations]
matekbd-keyboard-drawing.c:1612:3: warning: ‘gtk_style_context_get_background_color’ is deprecated: Use 'gtk_render_background' instead [-Wdeprecated-declarations]
matekbd-keyboard-drawing.c:2453:2: warning: ‘gtk_style_context_get_background_color’ is deprecated: Use 'gtk_render_background' instead [-Wdeprecated-declarations]
```

**Pull request closed without merging**
