### PR TITLE
Remove unused macros

### PR DESCRIPTION
**Pull request by sc0w**

### CODE REVIEW

**Comment by raveit65** [comment]
Second time, that you merge a commit without a approval!
Please wait for a reviewer.
And review older PRs from other team members, than someone will find time for your PRs.

**Comment by sc0w** [comment]
I am reviewing PRs every days, and I merge directly easy PRs which I consider it doesn't need to wait, I did it in the past, I did it now, and I will do it in the future and my work is **free**

I can't believe we are discussing a PR merged directly with 4 lines of unused macros removed

I don't understand why you hate me

**Comment by raveit65** [comment]
> I am reviewing PRs every days, and I merge directly easy PRs which I consider it doesn't need to wait, I did it in the past, I did it now, and I will do it in the future and my work is **free**
> 
> I can't believe we are discussing a PR merged directly with 4 lines of unused macros removed
> 
Everybody can make mistakes. For this reason a PR needs to be reviewed. Please be a team player.

> I don't understand why you hate me

Why? You should really review you English.

**Comment by sc0w** [comment]
I don't agree, but no problem, I will stop all my contributions, I hope now you will be happy

End of story

**Comment by raveit65** [comment]
Honestly, you can commit what you want.
I don't mind.

**Pull request merged**
