### PR TITLE
matekbd-keyboard-drawing: i18n symbolic names

### PR DESCRIPTION
**Pull request by rbuj**
To show keyboard layout
- Open mate-keyboard-properties
- Click on Layout tab
- Click on Show Button

Before

Captura de pantalla a 2020-01-24 10-24-25

After

Captura de pantalla a 2020-01-24 11-21-14

Edit:

Captura de pantalla a 2020-01-24 14-28-03

### CODE REVIEW

**Comment by raveit65** [comment]
In your screenshot the translation of eg. pg_up overrides th 9 on numblock. Is this nice?

**Comment by raveit65** [comment]
OK, with german keyboard layout everything is in english in the preview, same as before.
Personal i can live with it :)

**Comment by raveit65** [comment]
@rbuj 
The keypad looks a bit weird in your screenshot
73062101-df929500-3e9b-11ea-9133-20378ca7e912

**Comment by rbuj** [comment]
screenshot after reducing the font size:
Captura de pantalla a 2020-02-09 06-52-32

**Pull request merged**
