### PR TITLE
Fix some deprecations on Gtk3

### LINKED ISSUE #28: [GTK+3] Keyboard layout indicator text in the panel is always white
As seen in this screenshot https://i.imgur.com/VRBC772.jpg the indicator text that shows the current layout is white. And it is always white regardless of the theme being used. This happens _only_ on gtk3 builds. @raveit65 also confirmed this. libmatekbd version:
[*] libmatekbd-1.12.0_1             MATE keyboard library

### PR DESCRIPTION
**Pull request by XRevan86**
This also fixes #28 on supported themes.

### CODE REVIEW

**Comment by raveit65** [comment]
Thank you

**Comment by monsta** [comment]
Hmm... not sure how it happened, but now in GTK+2 build I have a black vertical line to the right of the indicator:
vertical_line

This happens with various themes - Menta, Mint-X, BlackMATE, TraditionalGreen... and the line is always black, no matter if the theme is light or dark.

**Comment by XRevan86** [comment]
@monsta, I don't see that right now.
I do see that bug occasionally with MATE for years though: black vertical line in na-tray.

**Comment by raveit65** [comment]
Not sure, but maybe m-p-m tray applet is started?
Same as in gtk+3.

**Comment by monsta** [comment]
Now I don't see it after restarting the panel a few times... oh well, so it looks unrelated to this PR.

**Pull request merged**
